# Generated by Django 4.2 on 2026-02-24 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=15)),
                ('username', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=45)),
                ('phone_number', models.CharField(max_length=12)),
                ('password', models.CharField(default='root', max_length=15)),
            ],
        ),
    ]
